# AvatarPvP Config
# Ask drtshock if you need help or have issues.
# $35 upfront and 20% of future gains.
# I will keep this plugin updated in the future :)
##################################################
############### Config starts here ###############
version: 0.1
FireNation:
  lightning:
    cooldown: 30
    radius: 10
    damage: 2
  fireball:
    cooldown: 3
EarthNation:
  golem:
    cooldown: 60
  fortify:
    cooldown: 60